# 日期时间相关函数
SELECT CURRENT_DATE() FROM DUAL;

SELECT CURRENT_TIME() FROM DUAL;

SELECT CURRENT_TIMESTAMP() FROM DUAL;

CREATE TABLE mes(id INT,content VARCHAR(30),sendtime DATETIME);
SELECT * FROM mes;
INSERT INTO mes 
	VALUES(1,'北京新闻',CURRENT_TIMESTAMP());
INSERT INTO mes VALUES(2,'上海新闻',NOW());
INSERT INTO mes VALUES(3,'广州新闻',NOW());

SELECT id,content,DATE(sendtime) FROM mes;
#十分钟内发布的新闻
SELECT * FROM mes 
	WHERE DATE_ADD(sendtime,INTERVAL 10 MINUTE) >= NOW() 
	
SELECT * FROM mes 
	WHERE sendtime >= DATE_SUB(NOW(),INTERVAL 20 MINUTE) 
 
SELECT CEILING(DATEDIFF('2011-11-11','1990-01-01') / 365) FROM DUAL;

SELECT DATEDIFF(NOW(),'1999-04-21') / 365 FROM DUAL;

SELECT DATEDIFF( DATE_ADD('1999-04-21',INTERVAL 80 YEAR),NOW()) FROM DUAL;

SELECT DATEDIFF('2079-04-21',NOW()) FROM DUAL;

SELECT YEAR(NOW()) FROM DUAL;
SELECT MONTH(NOW()) FROM DUAL;
SELECT DAY(NOW()) FROM DUAL;
SELECT YEAR('2013-11-10') FROM DUAL;

SELECT UNIX_TIMESTAMP() /(24 * 3600 * 365) FROM DUAL;












	
	